apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  labels:
    run: nginx-app-service
spec:
  type: NodePort
  selector:
    run: nginx-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30007

